services:
  db:
    image: timescale/timescaledb-ha:pg18-all-amd64
    container_name: pg18-all-amd64
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
